[tool.poetry]
name = "pureapi"
version = "1.1.0"
description = "Tools for working with Elsevier's Pure API."
readme = "README.md"
authors = ["David Naughton <naughton@umn.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "3.*.*"
addict = "*"
requests = "*"
tenacity = "*"

[tool.poetry.dev-dependencies]
pytest = "*"
python_dotenv = "*"
